apiVersion: v1
kind: Service
metadata:
  name: inventory
  labels:
    name: inventory
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30006
  selector:
    name: inventory
